version: '2'

services:
  sqlserver:
   image: microsoft/mssql-server-linux
   environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=YourStrong!Passw0rd
   ports:
    - 1433:1433
   logging:
     driver: "none"
   networks:
     vpcbr:
       ipv4_address: 10.5.0.5

  pymssql_x86_x64:
    image: quay.io/pypa/manylinux1_x86_64
    depends_on:
      - sqlserver
    volumes:
      - .:/io
    command:
      tail -f /dev/null
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6

  pymssql_i686:
    image: quay.io/pypa/manylinux1_i686
    depends_on:
    - sqlserver
    volumes:
    - .:/io
    command:
      tail -f /dev/null
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1

