version: 2
jobs:
    build:
        machine: true
        steps:
            - checkout
            - run:
                name: Start containers
                command: |
                  docker-compose up -d

            - run:
                name: Build x86_x64 wheels
                command: |
                  docker exec project_pymssql_x86_x64_1 ./io/dev/build_manylinux_wheels.sh

            - run:
                name: Build i686 wheels
                command: |
                  docker exec project_pymssql_i686_1 ./io/dev/build_manylinux_wheels.sh

            - run:
                name: Stop containers
                command: |
                  docker-compose down

            - persist_to_workspace:
                root: /home/circleci/project
                paths: .


    test:
        machine: true
        steps:
            - attach_workspace:
                at: /home/circleci/project

            - run:
                name: List directories to see if they persist across machine executors
                command: |
                  ls -la

            - run:
                name: Start containers
                command: |
                  docker-compose up -d

            - run:
                name: Test x86_x64 wheels
                command: |
                  docker exec project_pymssql_x86_x64_1 ./io/dev/test_manylinux_wheels.sh

            - run:
                name: Test i686 wheels
                command: |
                  docker exec project_pymssql_i686_1 ./io/dev/test_manylinux_wheels.sh

            - run:
                name: Stop containers
                command: |
                  docker-compose down

            - store_test_results:
                path: results/

            - store_artifacts:
                path: dist/

    deploy:
      docker:
        - image: circleci/python:3.6-stretch-browsers

      steps:
      - attach_workspace:
          at: /home/circleci/project

      - run:
          name: Circle Tag
          command: |
            echo '$CIRCLE_TAG'

      - run:
          name: alter path
          command: |
            export PATH=$PATH:/home/circleci/.local/bin:

      - run:
          name: Check and upload to PyPi
          command: |
            ./dev/deploy_manylinux_wheels.sh

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
          - test
