version: 2
jobs:
    build:
        machine: true

        steps:
            - checkout

            - run:
                name: folder listing for debugging
                command: ls -al

            - run:
                name: Build docker-compose containers
                command: |
                  docker-compose build

            - run:
                name: Start containers
                command: |
                  docker-compose up -d

            - run:
                name: List containers
                command: |
                  docker ps

            - run:
                name: Build x86_x64 wheels
                command: |
                  docker exec project_pymssql_x86_x64_1 ./io/dev/build_manylinux_wheels.sh

            - run:
                name: Test x86_x64 wheels
                command: |
                  docker exec project_pymssql_x86_x64_1 ./io/dev/test_manylinux_wheels.sh

            - run:
                name: Build i686 wheels
                command: |
                  docker exec project_pymssql_i686_1 ./io/dev/build_manylinux_wheels.sh

            - run:
                name: Test i686 wheels
                command: |
                  docker exec project_pymssql_i686_1 ./io/dev/test_manylinux_wheels.sh

            - run:
                name: Show results for test output validation
                command: |
                  ls -al ./results

            - run:
                name: Stop containers
                command: |
                  docker-compose down

            - store_test_results:
                path: ./results

            - store_artifacts:
                path: ./dist

