version: 2
jobs:
    build:
        machine: true

        steps:
            - checkout

            - run:
                name: folder listing for debugging
                command: ls -al

            - run:
                name: Build docker-compose containers
                command: |
                  docker-compose build

            - run:
                name: Start containers
                command: |
                  docker-compose up --abort-on-container-exit

            - run:
                name: Show directory after build and test
                command: |
                  ls -al

            - run:
                name: Show dists
                command: |
                  ls -al ./dist/

            - run:
                name: Stop containers
                command: |
                  docker-compose down

            - store_test_results:
                path: ./results

            - store_artifacts:
                path: ./dist

