name: Test

on:
  push:
    paths-ignore:
        - docs/**
        - ChangeLog*
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
        - docs/**
        - ChangeLog*

jobs:
  publish-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [2, 3.6, 3.7, 3.8, 3.9]
        os: [ubuntu-latest]

    services:
      SQLServer:
        image: mcr.microsoft.com/mssql/server:2017-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: sqlServerPassw0rd
        ports:
          - 1433:1433

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo apt-get install freetds-dev
          python -m pip install --upgrade pip
          pip install -r dev/requirements-dev.txt

      - name: build & install
        run: |
          python setup.py build install

      - name: Test with pytest
        run: |
          pytest -s

  publish-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        os: [windows-latest]
        python-architecture: [x64]

    services:
      SQLServer:
        image: mcr.microsoft.com/mssql/server:2017-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: sqlServerPassw0rd
        ports:
          - 1433:1433

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.python-architecture}}

      - name: Install vcpython27
        if: matrix.python-version == 2
        run: choco install vcpython27 -f -y

      - name: Install dependencies
        run: choco install gperf

      - name: Build wheels
        run: python dev/build_windows_wheels.py

      - name: build & install
        run: |
          python setup.py build install

      - name: Test with pytest
        run: |
          pytest -s


  publish-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        os: [macos-latest]

    services:
      SQLServer:
        image: mcr.microsoft.com/mssql/server:2017-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: sqlServerPassw0rd
        ports:
          - 1433:1433

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
              python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
              brew install freetds
              pip install --upgrade pip
              pip install -r dev/requirements-dev.txt

      - name: build & install
        run: |
          python setup.py build install

      - name: Test with pytest
        run: |
          pytest -s

